export const NEWS = [
  {
    id: 'n1',
    category: 'Keuangan Daerah',
    title: 'Pemerintah daerah diminta menuntaskan pembahasan rancangan APBD tepat waktu',
    excerpt: 'Kemendagri mengingatkan agar pembahasan rancangan APBD bersama DPRD diselesaikan sebelum batas waktu yang ditetapkan.',
    daysAgo: 0,
    tone: 'navy',
    icon: 'landmark',
  },
  {
    id: 'n2',
    category: 'Kependudukan',
    title: 'Layanan identitas kependudukan digital menjangkau lebih banyak kecamatan',
    excerpt: 'Aktivasi identitas kependudukan digital terus diperluas melalui layanan jemput bola di kantor kecamatan.',
    daysAgo: 1,
    tone: 'tan',
    icon: 'id',
  },
  {
    id: 'n3',
    category: 'Pemerintahan Desa',
    title: 'Pendampingan tata kelola dana desa diperkuat di wilayah timur Indonesia',
    excerpt: 'Pendampingan difokuskan pada perencanaan, pelaporan, dan transparansi penggunaan dana desa.',
    daysAgo: 2,
    tone: 'navy',
    icon: 'map',
  },
  {
    id: 'n4',
    category: 'Ekonomi Daerah',
    title: 'Rapat koordinasi pengendalian inflasi daerah digelar setiap pekan',
    excerpt: 'Pemerintah daerah memaparkan langkah stabilisasi harga bahan pokok dalam rapat koordinasi mingguan.',
    daysAgo: 3,
    tone: 'tan',
    icon: 'chart',
  },
  {
    id: 'n5',
    category: 'Kelembagaan',
    title: 'Pelantikan pejabat pimpinan tinggi pratama di lingkungan Kemendagri',
    excerpt: 'Pejabat yang dilantik diminta segera melakukan konsolidasi dan menjaga kesinambungan program unit kerja.',
    daysAgo: 5,
    tone: 'navy',
    icon: 'award',
  },
  {
    id: 'n6',
    category: 'Informasi Publik',
    title: 'Kanal permohonan informasi publik secara daring kini lebih mudah diakses',
    excerpt: 'Masyarakat dapat mengajukan dan memantau permohonan informasi publik melalui layanan daring PPID.',
    daysAgo: 6,
    tone: 'tan',
    icon: 'file',
  },
];
