'use client';

import { useEffect, useState } from 'react';
import { Download, FilePlus2, Trash2, X } from 'lucide-react';
import { apiDownload, apiFetch, apiUpload } from '@/lib/api';
import { useAuth } from '@/context/AuthProvider';
import { getLeader } from '@/lib/agenda-data';

const labels={PENDING:'Menunggu disposisi',ATTEND:'Pimpinan menghadiri',REPRESENTED:'Diwakilkan',NOT_ATTEND:'Tidak menghadiri'};
const fileLabels={INVITATION:'Undangan',DISPOSITION_MEMO:'Memo disposisi',OTHER:'Dokumen lain'};
export default function AgendaDetailAdmin({event,onClose,onChanged}){
 const {token,can}=useAuth();const[files,setFiles]=useState([]);const[attendanceStatus,setStatus]=useState(event?.attendanceStatus||'PENDING');const[name,setName]=useState(event?.representedByName||'');const[position,setPosition]=useState(event?.representedByPosition||'');const[note,setNote]=useState(event?.dispositionNote||'');const[fileType,setFileType]=useState('INVITATION');const[file,setFile]=useState(null);
 const load=async()=>{if(!event)return;try{const d=await apiFetch(`/agendas/${event.id}/files`,{token});setFiles(d.items||[])}catch(e){alert(e.message)}};
 useEffect(()=>{setStatus(event?.attendanceStatus||'PENDING');setName(event?.representedByName||'');setPosition(event?.representedByPosition||'');setNote(event?.dispositionNote||'');load()},[event?.id]);
 if(!event)return null;
 const saveDisposition=async()=>{try{await apiFetch(`/agendas/${event.id}/disposition`,{method:'PATCH',token,body:{attendanceStatus,representedByName:name,representedByPosition:position,dispositionNote:note}});await onChanged();alert('Disposisi tersimpan.')}catch(e){alert(e.message)}};
 const upload=async()=>{if(!file)return alert('Pilih file.');const fd=new FormData();fd.append('file',file);fd.append('fileType',fileType);try{await apiUpload(`/agendas/${event.id}/files`,fd,{token});setFile(null);await load()}catch(e){alert(e.message)}};
 const remove=async(id)=>{if(!confirm('Hapus file ini?'))return;try{await apiFetch(`/agendas/files/${id}`,{method:'DELETE',token});await load()}catch(e){alert(e.message)}};
 const download=async(f)=>{try{await apiDownload(`/agendas/files/${f.id}/download`,{token,filename:f.originalName})}catch(e){alert(e.message)}};
 return <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center sm:p-4"><div className="absolute inset-0 bg-navy-950/60" onClick={onClose}/><div className="relative max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-t-2xl bg-white p-6 shadow-2xl sm:rounded-2xl"><div className="flex items-start justify-between gap-4"><div><span className="rounded-full bg-red-50 px-2.5 py-1 text-xs font-bold text-red-700">INTERNAL / TERBATAS</span><h2 className="mt-3 font-serif text-2xl text-navy-900">{event.title}</h2><p className="mt-1 text-sm text-navy-500">{event.date} · {event.start}–{event.end} · {getLeader(event.leader).name}</p></div><button onClick={onClose} className="rounded-lg p-2 hover:bg-navy-50"><X className="h-5 w-5"/></button></div>
 <div className="mt-6 grid gap-6 lg:grid-cols-2"><section className="rounded-xl border border-navy-100 p-4"><h3 className="font-semibold text-navy-900">Memo Disposisi Pimpinan</h3><label className="label mt-4">Keputusan kehadiran</label><select className="input" value={attendanceStatus} onChange={e=>setStatus(e.target.value)} disabled={!can('agenda.disposition')}>{Object.entries(labels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select>{attendanceStatus==='REPRESENTED'&&<><label className="label mt-3">Diwakilkan kepada</label><input className="input" value={name} onChange={e=>setName(e.target.value)} disabled={!can('agenda.disposition')} placeholder="Nama pejabat yang mewakili"/><label className="label mt-3">Jabatan</label><input className="input" value={position} onChange={e=>setPosition(e.target.value)} disabled={!can('agenda.disposition')} placeholder="Jabatan"/></>}<label className="label mt-3">Catatan disposisi</label><textarea className="input resize-y" rows={4} value={note} onChange={e=>setNote(e.target.value)} disabled={!can('agenda.disposition')}/>{event.dispositionByName&&<p className="mt-2 text-xs text-navy-400">Terakhir oleh {event.dispositionByName}</p>}{can('agenda.disposition')&&<button className="btn-primary mt-4" onClick={saveDisposition}>Simpan disposisi</button>}</section>
 <section className="rounded-xl border border-navy-100 p-4"><h3 className="font-semibold text-navy-900">Undangan & Dokumen Agenda</h3>{files.length?<div className="mt-3 space-y-2">{files.map(f=><div key={f.id} className="flex items-center gap-2 rounded-lg bg-navy-50 p-3"><div className="min-w-0 flex-1"><div className="text-xs font-bold text-tan-700">{fileLabels[f.fileType]}</div><div className="truncate text-sm text-navy-800">{f.originalName}</div></div><button title="Unduh" onClick={()=>download(f)} className="rounded p-2 hover:bg-white"><Download className="h-4 w-4"/></button>{can('agenda.files')&&<button title="Hapus" onClick={()=>remove(f.id)} className="rounded p-2 text-red-700 hover:bg-white"><Trash2 className="h-4 w-4"/></button>}</div>)}</div>:<p className="mt-3 text-sm text-navy-400">Belum ada dokumen.</p>}{can('agenda.files')&&<div className="mt-4 border-t border-navy-100 pt-4"><div className="grid gap-2 sm:grid-cols-[160px_1fr]"><select className="input" value={fileType} onChange={e=>setFileType(e.target.value)}><option value="INVITATION">Undangan</option><option value="DISPOSITION_MEMO">Memo disposisi</option><option value="OTHER">Dokumen lain</option></select><input type="file" className="input py-2" onChange={e=>setFile(e.target.files?.[0]||null)}/></div><button className="btn-ghost mt-3" onClick={upload}><FilePlus2 className="h-4 w-4"/> Unggah file</button></div>}</section></div>
 </div></div>
}
