'use client';

import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { X } from 'lucide-react';
import { CATEGORIES, LEADERS } from '@/lib/agenda-data';
import { toKey, toMinutes } from '@/lib/date';
import { jakartaNow } from '@/hooks/useNow';

const empty=()=>({title:'',leader:'menteri',category:'rapat',date:toKey(jakartaNow()),start:'09:00',end:'10:00',location:'',description:''});
export default function EventForm({open,initial,onClose,onSubmit}){
 const [form,setForm]=useState(empty);const[errors,setErrors]=useState({});const isEdit=Boolean(initial?.id);
 useEffect(()=>{if(open){setForm(initial?{...empty(),...initial}:empty());setErrors({})}},[open,initial]);
 useEffect(()=>{if(!open)return;const onKey=e=>e.key==='Escape'&&onClose();window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[open,onClose]);
 const set=k=>e=>setForm(f=>({...f,[k]:e.target.value}));
 const validate=()=>{const n={};if(form.title.trim().length<5)n.title='Isi nama kegiatan minimal 5 karakter.';if(!form.date)n.date='Pilih tanggal kegiatan.';if(!form.start||!form.end)n.time='Isi jam mulai dan selesai.';else if(toMinutes(form.end)<=toMinutes(form.start))n.time='Jam selesai harus setelah jam mulai.';if(!form.location.trim())n.location='Isi lokasi kegiatan.';setErrors(n);return !Object.keys(n).length};
 const submit=e=>{e.preventDefault();if(!validate())return;const{id,...data}=form;onSubmit({...data,title:data.title.trim(),location:data.location.trim(),description:data.description.trim()})};
 return <AnimatePresence>{open&&<motion.div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center sm:p-4" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><div className="absolute inset-0 bg-navy-950/60 backdrop-blur-sm" onClick={onClose}/><motion.form onSubmit={submit} role="dialog" aria-modal="true" initial={{y:48,opacity:0}} animate={{y:0,opacity:1}} exit={{y:48,opacity:0}} className="relative flex max-h-[92vh] w-full max-w-2xl flex-col overflow-hidden rounded-t-2xl bg-white shadow-2xl sm:rounded-2xl"><div className="flex items-center justify-between border-b border-navy-100 px-6 py-4"><div><h2 className="font-serif text-xl text-navy-900">{isEdit?'Ubah agenda internal':'Tambah agenda internal'}</h2><p className="mt-1 text-xs text-navy-500">Agenda tidak pernah ditayangkan pada portal publik.</p></div><button type="button" onClick={onClose} className="rounded-lg p-2 text-navy-500 hover:bg-navy-50"><X className="h-5 w-5"/></button></div><div className="grid gap-5 overflow-y-auto px-6 py-6 sm:grid-cols-2"><Field label="Nama kegiatan" error={errors.title} className="sm:col-span-2"><input value={form.title} onChange={set('title')} className="input"/></Field><Field label="Pimpinan"><select value={form.leader} onChange={set('leader')} className="input">{LEADERS.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select></Field><Field label="Jenis kegiatan"><select value={form.category} onChange={set('category')} className="input">{CATEGORIES.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field><Field label="Tanggal" error={errors.date}><input type="date" value={form.date} onChange={set('date')} className="input"/></Field><Field label="Waktu (WIB)" error={errors.time}><div className="flex items-center gap-2"><input type="time" value={form.start} onChange={set('start')} className="input"/><span>–</span><input type="time" value={form.end} onChange={set('end')} className="input"/></div></Field><Field label="Lokasi" error={errors.location} className="sm:col-span-2"><input value={form.location} onChange={set('location')} className="input"/></Field><Field label="Keterangan internal" className="sm:col-span-2"><textarea value={form.description} onChange={set('description')} rows={4} className="input resize-y"/></Field></div><div className="flex flex-col-reverse gap-2 border-t border-navy-100 px-6 py-4 sm:flex-row sm:justify-end"><button type="button" onClick={onClose} className="btn-ghost">Batal</button><button className="btn-primary">{isEdit?'Simpan perubahan':'Simpan draft'}</button></div></motion.form></motion.div>}</AnimatePresence>
}
function Field({label,error,className='',children}){return <div className={className}><span className="label">{label}</span>{children}{error&&<p className="mt-1.5 text-sm text-red-700">{error}</p>}</div>}
